### ISSUE TITLE
Invalid issue, sorry!

### ISSUE THREAD

**Issue by floridop** [samandrw/MNXB11-homework#2]
Hi @samandrw 

sorry, this was a mistake, you can discard it. Closing.

**Comment by samandrw** [comment]
Hello, I am not entirely sure either, I did as requested and instructed in
the slides. I will ask my peers for advice on what they have done and how
to fix this. I posted a new permalink with my latest submission, hopefully
now the issue has been solved.
Best wishes, Sam
